# SPDX-FileCopyrightText: 2021-2024 The Ikarus Developers mueller@ibb.uni-stuttgart.de
# SPDX-License-Identifier: LGPL-3.0-or-later

name: CodeStyle

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/ghpages.yml'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '.github/workflows/ghpages.yml'

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}
      - uses: actions/checkout@v4
        with:
         path: 'repo'
      - name: Install format dependencies
        run: |
          pip install clang-format==18.1.8
          clang-format --version
          pip install cmake_format==0.6.13 pyyaml

      - name: configure
        run: cmake -S "cmake/FormatTarget" -Bbuild -DADD_FORMATTARGET=TRUE

      - name: check style
        run: |
          cmake --build build --target format
          cmake --build build --target check-format
